// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd15_R-AYWrwIM0d_pfSi1Tf7kStKDAeQ',
    appId: '1:331084011346:web:d63697c9d5ae770d3b4c8b',
    messagingSenderId: '331084011346',
    projectId: 'horoscope-89ef4',
    authDomain: 'horoscope-89ef4.firebaseapp.com',
    storageBucket: 'horoscope-89ef4.appspot.com',
    measurementId: 'G-5BD0BKK5TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9EPrvroWCVYILRpRjlwrhTQFkjbCjAVw',
    appId: '1:331084011346:android:77d18e372438af8f3b4c8b',
    messagingSenderId: '331084011346',
    projectId: 'horoscope-89ef4',
    storageBucket: 'horoscope-89ef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu2Lt2W6fCCgm9YCEEzDzsWCSRueBj_tY',
    appId: '1:331084011346:ios:b0598b5ee5ba70e63b4c8b',
    messagingSenderId: '331084011346',
    projectId: 'horoscope-89ef4',
    storageBucket: 'horoscope-89ef4.appspot.com',
    iosClientId: '331084011346-nidnamqfegpjqsb1qd5eeanehfr235nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationHoroscope',
  );
}
